### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by kiwi0fruit** [Antipurity/on-ai-article#1]
Hello. Thanks for a feedback. Some kind of feedback...

I've started reading your article but failed to comprehend what is the goal behind it. What do you want to achieve with it? If it's only about communicating some ideas then it lacks the "abstract" part where you list and consicely explain the ideas before expanding them. I guess goals and abstract would help to communicaste your thoughts.

Best regards,
Peter.

**Comment by Antipurity** [comment]
It is true that the common structure of scientific/philosophical articles is not present in this one. That viewpoint has been considered as only getting in the way of communicating ideas — a continuation of my coding practices, conflating complexity with code/text size (as is right) and minifying that to the extreme (and my extreme is pretty extreme).

Though it _has_ occured to me that perhaps I went too far, but the only way to fix it is to explain personally and answer questions; dialogue, even if the end is known.

The very notion of 'goal' and 'abstract' implies an imperfect logical viewpoint. If it is possible to write an 'abstract', then all that complex text is equivalent to that 'abstract' and should be replaced by it. Repeat that a few dozen times, and no one can understand it, even though clarity can not be higher.

You could say that the goal of this is to explain/understand everything to prepare for implementation, and the abstract is 'explains everything many times in different ways', but that's so banal that it's completely useless. (I included it anyway.) Should think not only about goals, but how other people view them — this text is for people, not for me, anyway.

In a way, this whole… article/text is an 'abstract'. An effort to unite all achievements of humanity into one; an imaginary prototype for the future real system. Any reduction that I can think of results in a loss of functionality. In fact, almost every sentence is equivalent to and is caused by the existence of a short function, and could easily have been the result of months of considerations.

(What is a highly-regarded wisdom/observation, able to earn thousands of upvotes on /r/philosophy when expressed, can take five words here and be never mentioned again. It is assumed that the reader has mastered order-independent logical/meaningful unification, and only needs to be told once — funny, requiring logic to understand logic; some form of bootstrapping is needed. But I can repeat if needed, adapted to the question: I _am_ this viewpoint, or include it, anyway.)

You could also say that understanding this article/text is an exercise/experiment in viewpoint self-similarity, a way to improve one's viewpoint of viewpoints. Though the peak is surrounded by an uncanny valley, getting to it is quite possible and worthwhile — and this article is designed to minimize the distance (or, complexity, defined by the size of internal representation). Still, may take a lot of effort, sorry.

From that perspective, it is a tool for self-similarity, a tool which I currently see no way to improve — but perhaps someone else can.

**Comment by kiwi0fruit** [comment]
Unfortunately that didn't help to understand you. I am of the opposite opinion: that if something doesn't have consice (really consice) abstract and goals formulated then it's not ready to be communicated to other people.

**Comment by Antipurity** [comment]
It does have really, really concise goals: 'do everything'; pretty sure the article mentions it many times. No other goals could suffice; no 'something' like historically was done. At the end of self-similarity, there is only 'everything'.

I agree with your opinion, but here, the question is not whether it has those — it's a question of how useful they would be. And they seem worse than useless, probably turning away people people with the thoughts "so obvious, I've seen it a million times — all of the attempts very bad, too ambitious, not thought-through, etc.".

…Though I might be opposed just because I am over-focused on code — uh I mean text — simplification. Have read barely any actual articles, so that need to adhere to that particular format, and to use the particular-to-knowledge-area magical words in it, is not strong at all. Not even sure what should be in that proposed abstract, besides the obvious.

It _is_ ready to be communicated to people. After many years of improvement, this is the product; what to do to improve further, implement it in code? I can probably do that, but it will take many more years. Of course, I am open to less drastic and cruel suggestions, which is (part of) why this article exists at all.

**Comment by kiwi0fruit** [comment]
Yep, there should be obvious or very simple to comprehend. At least at the beginning. Then there should be some implications from that basis.

The topic as I see it is almost about philosophy and math. And both should start from obvious otherwise they are useless in my opinion.

**Comment by kiwi0fruit** [comment]
As about 'do everything' -- this sentence doesn't have a meaning for me.

**Comment by Antipurity** [comment]
Yeah, that sentence doesn't really have a meaning for anyone. That's why I think including it is a bad idea.

Also, the topic itself is mind-breaking (too complicated and too alien), and it flows in the dependencies-first manner, which I call 'obvious first'. All efforts to optimize the understandability (by starting from 'the obvious', etc.) have so far been met with failure.

What is obvious is too dependent on the individual to be a good optimization criterion; I used a more logical/code-like approach than what seems like 'common sense', because it is not common and is not static and is not uniform, and is actually rather arbitrary. Defy what it seems to be human long enough, and what cannot be defied is what is actually to be human.

Anyway, I added some thing that I think is an abstract at the beginning. Is that what I think it is? Is that good? I don't know anything about abstracts.

**Comment by kiwi0fruit** [comment]
First part of the abstract has too many not yet defined terms that it seems lacking meaning. Except that there is something about abstract and very simple agents with goals that change environment.

The second part says that the main idea is to propose some new way to describe reality. Something like framework or understanding. What is looks like I didn't get.

**Comment by Antipurity** [comment]
Yes, that is exactly what I meant by 'cannot simplify the text further without losing functionality' (using undefined terms). But aren't abstracts essentially introductions, a super-short description, and do not _have_ to make sense if they can't?

Or if you are talking about "'anything' is undefined", it is defined by an equivalency, "anything" (or "thing") (the word, the concept) can be replaced by any particular thing in any context, and the other way around. Everything=something. Defining equivalencies is textbook defining of terms, defining is defining. (And definitions should not be in the abstract, right?)

"Something like framework or understanding" — yes, called a 'viewpoint' here; a thing that can change, an optimizer of what it does. In common usage, the 'thing' part correlates with programs or brains or personalities, and the 'change' part correlates with the meaning or goal (the particular words are often associated with a particular viewpoint, with no precise definitions to anything); basically, a program with meaning (meaningful to that program — defined by the viewpoint), or a personality with a goal. Should I define it in the text (or abstract)? Is the wording unclear — how to make it clearer?

I don't know what you are trying to say with the last sentences of each paragraph; parsing errors have occured. (Though it seems like you consider viewpoints to be either understood-now or didn't-get; the viewpoints presented here weren't built in a day, and the understanding won't be built in a day either, probably.)

**Comment by kiwi0fruit** [comment]
Abstarct should be crystal clear to the supposed audience. The new terms should be present only as the result of the work. And there should be explained what they mean, why exist and what help to accieve.

**Comment by kiwi0fruit** [comment]
"Whispers From the Chess Community" was a great read. Thanks!
